#pragma once

#include "vector2d.h"

#define MAX_TEXTURE_COUNT 64

enum {
	LAIN_ROOM,

	BEAR_ICON_ACTIVE,
	BEAR_ICON_INACTIVE,
	UI_LAIN_BEAR,
	UI_LAIN,
	MAIN_UI,
	MAIN_UI_BAR_ACTIVE,
	MAIN_UI_BAR_INACTIVE,
	DRESSUP_BUTTON_INACTIVE,
	DRESSUP_BUTTON_ACTIVE,
	THEATER_PREVIEWS,
	THEATER_BUTTON_ACTIVE,
	THEATER_BUTTON_INACTIVE,
	SCREWDRIVER_ICON_INACTIVE,
	PAW_ICON,
	SCORE_PREVIEW,

	RED_FONT_TEXTURE,
	WHITE_FONT_TEXTURE,

	KUMA_SHOOT_BG,
	KUMA_SHOOT_BUSH_OVERLAY,
	BROWN_BEAR_MOVE_RIGHT,
	WHITE_BEAR_MOVE_RIGHT,
	KUMA_SHOOT_SMOKE,
	KUMA_SHOOT_MIHO,
	KUMA_SHOOT_MIKA,
	KUMA_SHOOT_YASUO,
	KUMA_SHOOT_SCREWDRIVER_LAIN,
	KUMA_SHOOT_SCHOOL_LAIN,
	KUMA_SHOOT_DEFAULT_LAIN,
	KUMA_SHOOT_EXPLOSION,

	LAIN_CYBERIA_STANDING,
	LAIN_CYBERIA_LEAVE,
	LAIN_CYBERIA_MOVE_LEFT,

	LAIN_SCHOOL_STANDING,
	LAIN_SCHOOL_LEAVE,
	LAIN_SCHOOL_MOVE_LEFT,

	LAIN_ALIEN_STANDING,
	LAIN_ALIEN_LEAVE,
	LAIN_ALIEN_MOVE_LEFT,

	LAIN_PAJAMA_STANDING,
	LAIN_PAJAMA_LEAVE,
	LAIN_PAJAMA_MOVE_LEFT,

	LAIN_BEAR_STANDING,
	LAIN_BEAR_LEAVE,
	LAIN_BEAR_MOVE_LEFT,

	DRESSUP_BEAR_OUTFIT,
	DRESSUP_SCHOOL_OUTFIT,
	DRESSUP_PAJAMA_OUTFIT,
	DRESSUP_CYBERIA_OUTFIT,
	DRESSUP_UFO,
	DRESSUP_NAVI,
	DRESSUP_SCREWDRIVER,
};

typedef struct {
	GLuint id;
	int nr_channels;
	Vector2D size;
	char *name;
} Texture;

Texture make_texture(char *image_path, char *name);
void textures_init(Texture *textures);
